import { PERMISSION } from "./permission.types.js";

import type { Permission } from "./permission.types.js";

export const ADMIN_PERMISSIONS: ReadonlySet<Permission> = new Set<Permission>([
  PERMISSION.DASHBOARD_READ,

  PERMISSION.ACTIVITY_READ,
  PERMISSION.ACTIVITY_DELETE,
  PERMISSION.ACTIVITY_CLEAR,
  PERMISSION.ANALYTICS_READ,
  PERMISSION.ASK_LOOP_USE,

  PERMISSION.FEEDBACK_READ,
  PERMISSION.FEEDBACK_CREATE,
  PERMISSION.FEEDBACK_UPDATE,
  PERMISSION.FEEDBACK_DELETE,
  PERMISSION.FEEDBACK_IMPORT,
  PERMISSION.FEEDBACK_INBOX_MANAGE,

  PERMISSION.MEMBER_READ,
  PERMISSION.MEMBER_INVITE,
  PERMISSION.MEMBER_UPDATE_ROLE,
  PERMISSION.MEMBER_REMOVE,

  PERMISSION.NOTIFICATION_READ_OWN,
  PERMISSION.NOTIFICATION_UPDATE_OWN,
  PERMISSION.NOTIFICATION_BROADCAST,

  PERMISSION.PROFILE_READ_OWN,
  PERMISSION.PROFILE_UPDATE_OWN,

  PERMISSION.REPORT_READ,
  PERMISSION.REPORT_CREATE,
  PERMISSION.REPORT_UPDATE,
  PERMISSION.REPORT_DELETE,

  PERMISSION.SETTINGS_READ,
  PERMISSION.SETTINGS_UPDATE,
  PERMISSION.SETTINGS_RESET,

  PERMISSION.THEME_READ,
  PERMISSION.THEME_CREATE,
  PERMISSION.THEME_UPDATE,
  PERMISSION.THEME_DELETE,
  PERMISSION.THEME_GENERATE,

  PERMISSION.WORKSPACE_READ,
  PERMISSION.WORKSPACE_UPDATE,
  PERMISSION.WORKSPACE_ARCHIVE,
  PERMISSION.WORKSPACE_RESTORE,
  PERMISSION.WORKSPACE_DELETE,
]);
