import { PERMISSION } from "./permission.types.js";

import type { Permission } from "./permission.types.js";

export const ANALYST_PERMISSIONS: ReadonlySet<Permission> = new Set<Permission>(
  [
    PERMISSION.ACTIVITY_READ,
    PERMISSION.ANALYTICS_READ,
    PERMISSION.ASK_LOOP_USE,

    PERMISSION.FEEDBACK_READ,
    PERMISSION.FEEDBACK_CREATE,
    PERMISSION.FEEDBACK_UPDATE,
    PERMISSION.FEEDBACK_IMPORT,
    PERMISSION.FEEDBACK_INBOX_MANAGE,

    PERMISSION.MEMBER_READ,

    PERMISSION.NOTIFICATION_READ_OWN,
    PERMISSION.NOTIFICATION_UPDATE_OWN,

    PERMISSION.PROFILE_READ_OWN,
    PERMISSION.PROFILE_UPDATE_OWN,

    PERMISSION.REPORT_READ,
    PERMISSION.REPORT_CREATE,
    PERMISSION.REPORT_UPDATE,

    PERMISSION.SETTINGS_READ,
    PERMISSION.SETTINGS_UPDATE,
    PERMISSION.SETTINGS_RESET,

    PERMISSION.THEME_READ,
    PERMISSION.THEME_CREATE,
    PERMISSION.THEME_UPDATE,
    PERMISSION.THEME_GENERATE,

    PERMISSION.WORKSPACE_READ,
  ],
);
