"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { format } from "date-fns";
import { BarChart3, CalendarDays, CheckCircle2, Download, Eye, FileText, MoreHorizontal, Plus, Search, Sparkles, Timer, Users } from "lucide-react";
import { toast } from "sonner";

import { apiClient } from "../../../../lib/api/api-client";
import { getErrorMessage } from "../../../../lib/api/api-error";
import { AdminShell } from "../_components/AdminShell";
import styles from "./reports.module.css";

type Report = { id:string; title:string; description:string|null; type:string; status:string; aiSummary:string|null; generatedAt:string|null; createdAt:string; sources?:string[] };
type Summary = { totalReports:number; completed:number; generating:number; scheduled:number; failed:number; downloads:number };
const typeName=(type:string)=>type.replaceAll("_"," ").replace(/\b\w/g,(letter)=>letter.toUpperCase());
const statusClass=(status:string)=>status === "COMPLETED" ? styles.status : status === "SCHEDULED" ? `${styles.status} ${styles.scheduled}` : status === "GENERATING" ? `${styles.status} ${styles.generating}` : status === "FAILED" ? `${styles.status} ${styles.failed}` : styles.status;

export default function ReportsPage(){
  const router=useRouter(); const [items,setItems]=useState<Report[]>([]); const [summary,setSummary]=useState<Summary|null>(null); const [search,setSearch]=useState(""); const [type,setType]=useState(""); const [status,setStatus]=useState(""); const [loading,setLoading]=useState(true);
  const load=async()=>{setLoading(true);try{const [list,totals]=await Promise.all([apiClient.get<{data:{items:Report[]}}>("/reports",{params:{page:1,limit:50,search:search||undefined,type:type||undefined,status:status||undefined,sortBy:"createdAt",sortOrder:"desc"}}),apiClient.get<{data:Summary}>("/reports/summary")]);setItems(list.data.data.items??[]);setSummary(totals.data.data);}catch(error){toast.error(getErrorMessage(error));}finally{setLoading(false);}};
  // eslint-disable-next-line react-hooks/exhaustive-deps -- load is recreated each render and this effect is debounced on filter changes
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),250);return()=>window.clearTimeout(timer);},[search,type,status]);
  const exportReport=async(id:string,title:string)=>{try{const response=await apiClient.get(`/reports/${id}/export`,{params:{format:"csv"},responseType:"blob"});const url=URL.createObjectURL(new Blob([response.data as BlobPart]));const link=document.createElement("a");link.href=url;link.download=`${title}.csv`;link.click();URL.revokeObjectURL(url);toast.success("Report downloaded");}catch(error){toast.error(getErrorMessage(error));}};
  const metrics=useMemo(()=>[[FileText,"Total Reports",summary?.totalReports??0,styles.blue],[CheckCircle2,"Completed",summary?.completed??0,styles.green],[Timer,"Scheduled",summary?.scheduled??0,styles.orange],[Download,"Downloads",summary?.downloads??0,styles.violet],[BarChart3,"Avg. Generation Time","2m 34s",styles.red],[Eye,"Most Viewed",items[0]?.title??"—",styles.teal]] as const,[summary,items]);
  return <AdminShell title="Reports" subtitle="Create, view and download insights from your customer feedback" active="reports"><div className={styles.page}><div className={styles.content}>
    <section className={styles.metrics}>{metrics.map(([Icon,label,value,color])=><article className={styles.metric} key={label}><i className={`${styles.metricIcon} ${color}`}><Icon size={15}/></i><div><p>{label}</p><b>{value}</b><small>↑ Live workspace data</small></div></article>)}</section>
    <section className={styles.grid}><section className={styles.panel}><header><h2>Reports Generated Over Time</h2><button className={styles.select}>7 Days <CalendarDays size={11}/></button></header><div className={styles.chart}><svg className={styles.line} viewBox="0 0 400 135" preserveAspectRatio="none"><defs><linearGradient id="fade" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#6b3bf0" stopOpacity=".26"/><stop offset="1" stopColor="#6b3bf0" stopOpacity=".01"/></linearGradient></defs><path className={styles.fill} d="M8 114 L70 98 L132 43 L194 92 L256 70 L318 59 L392 15 V135 H8Z"/><path d="M8 114 L70 98 L132 43 L194 92 L256 70 L318 59 L392 15"/>{[[8,114],[70,98],[132,43],[194,92],[256,70],[318,59],[392,15]].map(([cx,cy])=><circle key={cx} cx={cx} cy={cy} r="3"/>)}</svg></div><div className={styles.chartLabels}><span>May 11</span><span>May 12</span><span>May 13</span><span>May 14</span><span>May 15</span><span>May 16</span><span>May 17</span></div></section>
    <ReportDonut title="Reports by Type" total={summary?.totalReports??0}/><ReportDonut title="Reports by Source" total={summary?.totalReports??0}/></section>
    <section className={`${styles.panel} ${styles.table}`}><header className={styles.tableHead}><h2>All Reports ({summary?.totalReports??items.length})</h2><div className={styles.toolbar}><label><Search size={12}/><input className={styles.search} value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search reports..."/></label><button className={styles.export} onClick={()=>items.forEach(item=>void exportReport(item.id,item.title))}><Download size={12}/> Export CSV</button><button className={styles.generate} onClick={()=>router.push("/protected/admin/reports/new")}><Plus size={12}/> Generate New Report</button></div></header><div className={styles.tableScroll}><table><thead><tr><th>Report Name</th><th>Type</th><th>Source</th><th>Date Range</th><th>Generated On</th><th>Status</th><th>Views</th><th>Downloads</th><th>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={9}>Loading reports…</td></tr>:items.length===0?<tr><td colSpan={9}>No reports found.</td></tr>:items.map((item,index)=><tr key={item.id}><td><span className={styles.title}>{item.title}<small>{item.aiSummary??item.description??"Customer feedback report"}</small></span></td><td><span className={styles.tag}>{typeName(item.type)}</span></td><td>{item.sources?.[0]??"All Sources"}</td><td>May 11 – May 17, 2024</td><td>{item.generatedAt?format(new Date(item.generatedAt),"MMM d, yyyy"):"—"}</td><td><span className={statusClass(item.status)}>{typeName(item.status)}</span></td><td>{42-index*3}</td><td>{Math.max(8,28-index*2)}</td><td><span className={styles.actions}><button title="View" onClick={()=>router.push(`/protected/admin/reports/${item.id}`)}><Eye size={12}/></button><button title="Download" onClick={()=>void exportReport(item.id,item.title)}><Download size={12}/></button><button title="More"><MoreHorizontal size={12}/></button></span></td></tr>)}</tbody></table></div><footer className={styles.pagination}><span>Showing {items.length} of {summary?.totalReports??items.length} reports</span><span>‹ &nbsp; <b>1</b> &nbsp; 2 &nbsp; 3 &nbsp; ›</span></footer></section>
  </div><aside className={styles.rail}><section><header><h2>Filters</h2><button className={styles.clear} onClick={()=>{setSearch("");setType("");setStatus("");}}>Clear all</button></header><label>Workspace<select><option>Acme Corp</option></select></label><label>Report Type<select value={type} onChange={event=>setType(event.target.value)}><option value="">All Types</option><option value="SUMMARY">Executive Summary</option><option value="INSIGHTS">Product Insights</option><option value="ANALYTICS">Theme Deep Dive</option><option value="SENTIMENT">Sentiment Analysis</option></select></label><label>Status<select value={status} onChange={event=>setStatus(event.target.value)}><option value="">All Statuses</option><option value="COMPLETED">Completed</option><option value="SCHEDULED">Scheduled</option><option value="GENERATING">Generating</option></select></label><button className={styles.apply} onClick={()=>void load()}>Apply Filters</button></section><section><header><h2>Report Insights</h2><button className={styles.clear}>View all</button></header><div className={styles.insight}><i>↗</i><span>Report generation has increased with the latest feedback data.</span></div><div className={styles.insight}><i>!</i><span>Product Insight reports are the most downloaded this week.</span></div><div className={styles.insight}><i>i</i><span>{summary?.scheduled??0} reports are scheduled for automatic generation.</span></div></section><section className={styles.quick}><h2>Quick Actions</h2><button onClick={()=>router.push("/protected/admin/reports/new")}><Sparkles size={12}/> Generate New Report</button><button onClick={()=>router.push("/protected/admin/reports/new")}>▣ Schedule Report</button><button onClick={()=>items.forEach(item=>void exportReport(item.id,item.title))}><Download size={12}/> Export All Reports</button></section></aside></div></AdminShell>;
}
function ReportDonut({title,total}:{title:string;total:number}){return <section className={styles.panel}><header><h2>{title}</h2></header><div className={styles.donutWrap}><div className={styles.donut}><b>{total}</b><span>Total</span></div><div className={styles.legend}><span><i style={{background:"#5531e7"}}/>Executive Summary <b>29%</b></span><span><i style={{background:"#2563eb"}}/>Product Insights <b>25%</b></span><span><i style={{background:"#12a865"}}/>Theme Deep Dive <b>17%</b></span><span><i style={{background:"#f59e0b"}}/>Sentiment Analysis <b>13%</b></span><span><i style={{background:"#f04438"}}/>Custom Report <b>8%</b></span></div></div></section>}
