-- This migration intentionally does nothing.
-- The database objects it previously attempted to create were already created in earlier migrations:
--   - NotificationType and Notification were created in 20260724071629_create_analytics_migrate
--   - Notification was later expanded in 20260725195818_add_notifications
--   - Report and its initial indexes/foreign keys were created in 20260724071629_create_analytics_migrate
--   - Report was expanded in 20260725074443_expand_report_module
--
-- Keeping this file as a no-op preserves the migration history without re-creating existing production tables,
-- enums, indexes, or foreign keys.
--
-- This avoids destructive changes while allowing Prisma to advance migration state safely.
