export const NOTIFICATION_TYPES = {
  FEEDBACK_RECEIVED: "FEEDBACK_RECEIVED",
  FEEDBACK_ASSIGNED: "FEEDBACK_ASSIGNED",
  FEEDBACK_STATUS_CHANGED: "FEEDBACK_STATUS_CHANGED",
  REPORT_READY: "REPORT_READY",
  REPORT_FAILED: "REPORT_FAILED",
  MEMBER_ADDED: "MEMBER_ADDED",
  MEMBER_REMOVED: "MEMBER_REMOVED",
  WORKSPACE_SETTINGS_CHANGED: "WORKSPACE_SETTINGS_CHANGED",
  MENTION: "MENTION",
  SYSTEM: "SYSTEM",
} as const;

export type NotificationType = (typeof NOTIFICATION_TYPES)[keyof typeof NOTIFICATION_TYPES];

export const NOTIFICATION_TYPE_LABELS: Record<NotificationType, string> = {
  [NOTIFICATION_TYPES.FEEDBACK_RECEIVED]: "Feedback Received",
  [NOTIFICATION_TYPES.FEEDBACK_ASSIGNED]: "Feedback Assigned",
  [NOTIFICATION_TYPES.FEEDBACK_STATUS_CHANGED]: "Feedback Status Changed",
  [NOTIFICATION_TYPES.REPORT_READY]: "Report Ready",
  [NOTIFICATION_TYPES.REPORT_FAILED]: "Report Failed",
  [NOTIFICATION_TYPES.MEMBER_ADDED]: "Member Added",
  [NOTIFICATION_TYPES.MEMBER_REMOVED]: "Member Removed",
  [NOTIFICATION_TYPES.WORKSPACE_SETTINGS_CHANGED]: "Workspace Settings Changed",
  [NOTIFICATION_TYPES.MENTION]: "Mention",
  [NOTIFICATION_TYPES.SYSTEM]: "System",
};

export const NOTIFICATION_PRIORITIES = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  URGENT: "URGENT",
} as const;

export type NotificationPriority = (typeof NOTIFICATION_PRIORITIES)[keyof typeof NOTIFICATION_PRIORITIES];

export const NOTIFICATION_PRIORITY_LABELS: Record<NotificationPriority, string> = {
  [NOTIFICATION_PRIORITIES.LOW]: "Low",
  [NOTIFICATION_PRIORITIES.MEDIUM]: "Medium",
  [NOTIFICATION_PRIORITIES.HIGH]: "High",
  [NOTIFICATION_PRIORITIES.URGENT]: "Urgent",
};
