export const PAGINATION_DEFAULTS = {
  PAGE: 1,
  LIMIT: 10,
  MAX_LIMIT: 100,
} as const;

export const PAGINATION_SORT_ORDERS = {
  ASC: "asc",
  DESC: "desc",
} as const;

export type SortOrder = (typeof PAGINATION_SORT_ORDERS)[keyof typeof PAGINATION_SORT_ORDERS];

export const PAGINATION_DEFAULTS_STRICT = {
  DEFAULT_PAGE: PAGINATION_DEFAULTS.PAGE,
  DEFAULT_LIMIT: PAGINATION_DEFAULTS.LIMIT,
  DEFAULT_MAX_LIMIT: PAGINATION_DEFAULTS.MAX_LIMIT,
  DEFAULT_SORT_ORDER: PAGINATION_SORT_ORDERS.DESC,
} as const;
