export const PERMISSIONS = {
  CAN_MANAGE_WORKSPACE: "canManageWorkspace",
  CAN_MANAGE_MEMBERS: "canManageMembers",
  CAN_MANAGE_SETTINGS: "canManageSettings",
  CAN_MANAGE_FEEDBACK: "canManageFeedback",
  CAN_VIEW_ANALYTICS: "canViewAnalytics",
  CAN_GENERATE_REPORTS: "canGenerateReports",
  CAN_USE_ASK_LOOP: "canUseAskLoop",
  CAN_EXPORT_DATA: "canExportData",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<string, readonly Permission[]> = {
  ADMIN: [
    PERMISSIONS.CAN_MANAGE_WORKSPACE,
    PERMISSIONS.CAN_MANAGE_MEMBERS,
    PERMISSIONS.CAN_MANAGE_SETTINGS,
    PERMISSIONS.CAN_MANAGE_FEEDBACK,
    PERMISSIONS.CAN_VIEW_ANALYTICS,
    PERMISSIONS.CAN_GENERATE_REPORTS,
    PERMISSIONS.CAN_USE_ASK_LOOP,
    PERMISSIONS.CAN_EXPORT_DATA,
  ],
  ANALYST: [
    PERMISSIONS.CAN_MANAGE_FEEDBACK,
    PERMISSIONS.CAN_VIEW_ANALYTICS,
    PERMISSIONS.CAN_GENERATE_REPORTS,
    PERMISSIONS.CAN_USE_ASK_LOOP,
    PERMISSIONS.CAN_EXPORT_DATA,
  ],
  VIEWER: [
    PERMISSIONS.CAN_VIEW_ANALYTICS,
  ],
} as const;

export const PERMISSION_LABELS: Record<Permission, string> = {
  [PERMISSIONS.CAN_MANAGE_WORKSPACE]: "Manage Workspace",
  [PERMISSIONS.CAN_MANAGE_MEMBERS]: "Manage Members",
  [PERMISSIONS.CAN_MANAGE_SETTINGS]: "Manage Settings",
  [PERMISSIONS.CAN_MANAGE_FEEDBACK]: "Manage Feedback",
  [PERMISSIONS.CAN_VIEW_ANALYTICS]: "View Analytics",
  [PERMISSIONS.CAN_GENERATE_REPORTS]: "Generate Reports",
  [PERMISSIONS.CAN_USE_ASK_LOOP]: "Use Ask Loop",
  [PERMISSIONS.CAN_EXPORT_DATA]: "Export Data",
};
